export const COURSE_SERVICE = Symbol('COURSE_SERVICE');
export const COURSE_REPOSITORY = Symbol('COURSE_REPOSITORY');
export const COURSE_SCRAPPER_PORT = Symbol('COURSE_SCRAPPER_PORT');
export const COURSE_SERVICE_PRODUCER = Symbol('COURSE_SERVICE_PRODUCER');
